"""Eular Problem 12 - :
    What is the value of the first triangle number to have over five hundred
    divisors?
"""

import primes
import timer

DESC = 'Triangle numbers'
SOLUTION = 76576500


def triangles():
    """ Defines a generator that generates triangle numbers. The sequence of
        triangle numbers is generated by adding the natural numbers. The first
        triangle number is 1, followed by 3, 6, 10, and so on.
    """
    x = 1
    tri = 1
    while True:
        yield tri
        x += 1
        tri += x


@timer.timeit
def solve():
    result = 0
    for result in triangles():
        # Skip checking numbers that don't end in 0.
        if result % 10 != 0:
            continue
        f = primes.divisors(result)

        if len(f) > 500:
            break
    return result
