# coding=utf-8
eular1 = """Eular problem 1 - Multiples of 3 and 5:
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
"""

eular2 = """Eular problem 2 - Even Fibonacci numbers:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 4 million, find
the sum of the even-valued terms.
"""

eular3 = """Eular Problem 3 - Largest Prime Factor:
The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number
600,851,475,143 ?
"""

eular4 = """Eular problem 4 - Largest palindrome product:
A palindromic number reads the same both ways. The largest palindrome made from the product of
two 2-digit numbers is 9009 = 91 Ã—99. Find the largest palindrome made from the product of two
3-digit numbers.
"""

eular5 = """Eular problem 5 - Smallest multiple:
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any
remainder. What is the smallest positive number that is evenly divisible by all of the numbers
from 1 to 20?
"""

eular6 = """Eular Problem 6 - Sum square difference:
Find the difference between the sum of the squares of the first one hundred natural numbers and
the square of the sum.
"""

eular7 = """Eular Problem 7 - 10001st prime:
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is
13.What is the 10001st prime number?
"""

eular8 = """Eular Problem 8 - Largest product in a series:
Find the 13 adjacent digits in the 1000-digit number that have the greatest product. What is the
value of this product?
"""

eular9 = """Eular Problem 9 - Special Pythagorean triplet:
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a^2 + b^2 = c^2.
For example, 3^2 + 4^2 = 9 + 16 = 25 = 52. There exists exactly one Pythagorean triplet for which
a + b + c = 1000. Find the product a * b * c.
"""
