# coding=utf-8
eular1 = """Eular problem 1 - Multiples of 3 and 5:
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
"""

eular2 = """Eular problem 2 - Even Fibonacci numbers:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 4 million, find
the sum of the even-valued terms.
"""

eular3 = """Eular Problem 3 - Largest Prime Factor:
The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number
600,851,475,143 ?
"""

eular4 = """Eular problem 4 - Largest palindrome product:
A palindromic number reads the same both ways. The largest palindrome made from the product of
two 2-digit numbers is 9009 = 91 Ã—99. Find the largest palindrome made from the product of two
3-digit numbers.
"""

eular5 = """Eular problem 5 - Smallest multiple:
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any
remainder. What is the smallest positive number that is evenly divisible by all of the numbers
from 1 to 20?
"""

eular6 = """Eular Problem 6 - Sum square difference:
Find the difference between the sum of the squares of the first one hundred natural numbers and
the square of the sum.
"""

eular7 = """Eular Problem 7 - 10001st prime:
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is
13.What is the 10001st prime number?
"""

eular8 = """Eular Problem 8 - Largest product in a series:
Find the 13 adjacent digits in the 1000-digit number that have the greatest product. What is the
value of this product?
"""

eular9 = """Eular Problem 9 - Special Pythagorean triplet:
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a^2 + b^2 = c^2.
For example, 3^2 + 4^2 = 9 + 16 = 25 = 52. There exists exactly one Pythagorean triplet for which
a + b + c = 1000. Find the product a * b * c.
"""

eular10 = """Eular Problem 10 - Summation of primes:
Find the sum of all the primes below two million.
"""

eular11 = """Eular Problem 11 - Largest product in a grid:
In the 20×20 grid below, four numbers along a diagonal line have been marked in red. What is the
greatest product of four adjacent numbers in the same direction(up, down, left, right, or
diagonally) in the 20×20 grid?
"""

eular12 = """Eular Problem 12 - Triangle numbers:
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle
number would be: 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

What is the value of the first triangle number to have over five hundred divisors?
"""

eular13 = """Eular Problem 13 - Large Sum:
Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.
"""

eular14 = """Eular Problem 14 - Longest Collatz sequence:
Which starting number, under one million, produces the longest chain?
"""

eular15 = """Eular Problem 15 - Lattice paths:
Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down,
there are exactly 6 routes to the bottom right corner. How many such routes are there through a
20×20 grid?
"""

eular16 = """Eular Problem 16 - Power digit sum:
2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
What is the sum of the digits of the number 2^1000?
"""

eular17 = """Eular Problem 17 - Number letter counts:
If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are
3 + 3 + 5 + 4 + 4 = 19 letters used in total. If all the numbers from 1 to 1000 (one thousand)
inclusive were written out in words, how many letters would be used?

NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23
letters and 115 (one hundred and fifteen) contains 20 letters. (Note: The use of "and" when
writing out numbers is in compliance with British usage.
"""

eular18 = """Eular Problem 18 - Maximum path sum I:
By starting at the top of the triangle below and moving to adjacent numbers on the row below,
the maximum total from top to bottom is 23.
3
7 4
2 4 6
Find the maximum total from top to bottom of the given triangle:
"""

eular19 = """ Eular problem 19 - Counting Sundays:
How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31
Dec 2000)?
"""

eular20 = """Eular Problem 20 - Factorial digit sum:
n! means n × (n − 1) × ... × 3 × 2 × 1
For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800, and the sum of the digits in the number
10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27. Find the sum of the digits in the number 100!
"""

eular21 = """Eular Problem 21 - Amicable numbers:
Evaluate the sum of all the amicable numbers under 10000.
"""

eular22 = """Eular Problem 22 - Names scores:
Using names.txt, work out the alphabetical value for each name, multiply this value by its
alphabetical position in the list to obtain a name score.
What is the total of all the name scores in the file?
"""

eular23 = """Eular Problem 23 - Non-abundant sums:
A perfect number is a number for which the sum of its proper divisors is exactly equal to the
number. A number n is called deficient if the sum of its proper divisors is less than n and it
is called abundant if this sum exceeds n.

Find the sum of all the positive integers which cannot be written as the sum of
two abundant numbers.
"""

eular24 = """Eular Problem 24 - Lexicographic permutations:
What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?
"""

eular25 = """Eular Problem 25 - The Fibonacci sequence:
What is the first term in the Fibonacci sequence to contain 1000 digits?
"""
